### ISSUE TITLE
imscp2 programming language info

### ISSUE THREAD

**Issue by topstarnetwork** [i-MSCP/imscp2#1]
Hello!
I checked in your github repository for imscp and all I see is only php programming language,
if I refer myself to http://www.vhcs.net/about/technology.htm
do you still use same programming language as described in vhcs such as;

The VHCS software is written in PHP, Perl and C:

    VHCS GUI is written in PHP, a language explicitly designed to be embedded in web pages.
    VHCS Daemon is written in C
    VHCS Engine is written in Perl, a language explicitly designed for system management 

If not please tell me,
regards, Heather

**Comment by nuxwin** [comment]
Perl code: https://github.com/i-MSCP/imscp/tree/1.2.x/engine
C code: https://github.com/i-MSCP/imscp/tree/1.2.x/daemon

**Comment by topstarnetwork** [comment]
Thanks for this enlightment,
I found also another fork of vhcs here http://de.wikipedia.org/wiki/EasySCP
Could you please tell me if this is the same as yours or a more advanced updated software,
regards, Heather

**Comment by nuxwin** [comment]
Re,

Both i-MSCP and EasySCP projects are fork of the ispCP project (died project) which was itself a fork of VHCS.

Both are not comparable. i-MSCP is under heavy development. Just look at the community activities to know which project is more advanced than the other.

i-MSCP forum: http://i-mscp.net/index.php/BoardList/
EasySCP forum: http://www.easyscp.net/forum/index.php/BoardList/

**Comment by topstarnetwork** [comment]
Thanks! 
As long as  i-MSCP is not dead and will always be  under heavy development, then  i-MSCP will be the one to go with.
